
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RichieZhl/AllDemo
          searchPaths: spring-cloud/configs
  application:
    name: config-server